name: Go Restful API 

on: 
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Go environment
          uses: actions/setup-go@v4
          with: 
            go-version: 1.21
        
        - name: Install dependencies
          run: go mod tidy

        - name: Run tests
          run: go test ./...

        - name: Log in Docker Hub
          uses: docker/login-action@v2
          with: 
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: Build and push Docker images
          run: |
            docker build -t ${{secrets.DOCKER_USERNAME}}/go-restful-api .
            docker push ${{secrets.DOCKER_USERNAME}}/go-restful-api